# Generated by Django 2.1.7 on 2019-05-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_date',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='up_votes',
        ),
        migrations.AddField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
